export const SHOW_LOGIN_COMPONENT = 'SHOW_LOGIN_COMPONENT';  
export const SHOW_ADMIN_PRODUCT_CONFIG_CONTAINER = 'SHOW_ADMIN_PRODUCT_CONFIG_CONTAINER';  
export const PRODUCTS_LIST = 'PRODUCTS_LIST';  
export const CART_LIST = 'CART_LIST';  
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';  
export const REMOVE_ITEM_TO_CART = 'REMOVE_ITEM_TO_CART';
export const FETCH_USER_INFO_PENDING = 'FETCH_USER_INFO_PENDING';
export const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_PRODUCTS_LIST_PENDING = 'FETCH_PRODUCTS_LIST_PENDING';
export const FETCH_PRODUCTS_LIST_ERROR = 'FETCH_PRODUCTS_LIST_ERROR';
export const FETCH_PRODUCTS_LIST_SUCCESS = 'FETCH_PRODUCTS_LIST_SUCCESS';
export const SHOULD_UPDATE_PRODUCTS_LIST = 'SHOULD_UPDATE_PRODUCTS_LIST';
export const SHOW_ADMIN_CATEGORY_CONFIG_CONTAINER = 'SHOW_ADMIN_CATEGORY_CONFIG_CONTAINER';
export const SHOW_HINT_CONTAINER = 'SHOW_HINT_CONTAINER';


